require File.dirname(__FILE__) + "/intel_galileo/version"
require File.dirname(__FILE__) + "/intel_galileo/gpio"
require File.dirname(__FILE__) + "/intel_galileo/analog_in_pin"
require File.dirname(__FILE__) + "/intel_galileo/digital_pin"
require File.dirname(__FILE__) + "/intel_galileo/pwm"
